project:
  type: website
  output-dir: docs

website:
  title: "Trials in Pictures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/week-01.qmd
        text: Week 1

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    code-fold: true
    code-summary: "Show code"
    number-sections: false



